services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cv_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      # - N8N_BASIC_AUTH_USER=admin
      # - N8N_BASIC_AUTH_PASSWORD=securepassword123
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - GENERIC_TIMEZONE=Asia/Manila
      - N8N_LOG_LEVEL=debug
    volumes:
      - n8n_data:/home/node/.n8n

  web:
    build:
      context: ./
      dockerfile: ./infrastructure/docker/web/development/Dockerfile
    restart: always
    image: web
    ports:
      - '3000:3000'

volumes:
  pgdata:
  n8n_data:
